### ISSUE TITLE
Cannot change owner and permissions of ‘/var/lib/postgresql/data

### ISSUE THREAD

**Issue by matte0080** [timescale/helm-charts#325]
Hi mate,

install: cannot change owner and permissions of ‘/var/lib/postgresql/data’: No such file or directory
install: cannot change owner and permissions of ‘/var/lib/postgresql/wal/pg_wal’: No such file or directory

with helm creation of timescaledb-single i received this error. I'm running k8s on minikube.

Any ideas?

**Comment by npakudin** [comment]
@matte0080 did you resolve this issue? I have the same one

**Comment by npakudin** [comment]
For me the problem was that minikube creates a cluster with default size 20Gb for everything (including persistence volumes)
So k8s showed persistence volume size 120Gib, but the real size was 17Gib
When it exceeds on restore,
pgrestback renamed `/var/lib/postgresql/wal/pg_wal` to `/var/lib/postgresql/wal/pg_wal_2022-01-21-00-29-45`
and on restart pod couldn't find the wal directory and failed

For me helped

```
minikube delete
minikube start --driver=hyperkit --disk-size 180GB
```

**Comment by mathisve** [comment]
For anyone not using docker instead of hyperkit as a driver, I'd like to add that increasing the disk size with the docker driver works too!

**Comment by paulfantom** [comment]
Seems like this is not related to chart but to the environment. As such I am closing this issue.
