### ISSUE TITLE
Find read replica for timescaledb single helm chart

### ISSUE THREAD

**Issue by yspassivelogic** [timescale/helm-charts#609]
We deployed timescaledb single helm chart with 2 timescaledb pods  - 

```
% kubectl get pods -n timescaledb
NAME                                 READY   STATUS      RESTARTS   AGE
timescaledb-0                        2/2     Running     0          15d
timescaledb-1                        2/2     Running     0          15d
```

Time to time we see our app - hitting an error that "cannot execute INSERT a read only transaction"

We have a internal load balancer with a selectors:

 app: timescaledb
  role: master

Why is is trying to send db requests to timescaledb-1 ? is it because round robin of the load balancer and selectors?

**Comment by yspassivelogic** [comment]
any response on this?

**Comment by may-cDev** [comment]
So you're using your own, custom load balancer in order to route your requests?
Probably this is the issue, since I assume your load balancer does not know which timescale pod is currently the master. 

TimescaleDB uses patroni in the background to manage the timescale cluster and route your request to the correct host. You might want to route your traffic via the deployed timescale service (see template svc-timescaledb.yaml ) instead of your custom load balancer.

**Comment by yspassivelogic** [comment]
hi @may-cDev - the problem is my application which is another pod is having issues connecting to the svc-timescaledb.yaml 

in order for my app to connect (which is another pod)- do you suggest I use a NodePort or clusterIP?
